privileges:
  service:
    port: 8050
    image:
      name: fairay/rsoi-lab5-privileges
      version: latest
    database:
      name: privileges
flights:
  service:
    port: 8060
    image:
      name: fairay/rsoi-lab5-flights
      version: latest
    database:
      name: flights
tickets:
  service:
    port: 8070
    image:
      name: fairay/rsoi-lab5-tickets
      version: latest
    database:
      name: tickets
gateway:
  service:
    port: 8080
    image:
      name: fairay/rsoi-lab5-gateway
      version: latest
    ingress:
      enabled: true
      path: /
      pathType: Prefix
